# 15. Using finally in Exception Handling
def demonstrate_finally():
    try:
        print("Trying to execute...")
    finally:
        print("This always executes!")
